name: pebebe
description: "Aplikasi pelaporan barang hilang/ditemukan di kampus (Offline-first MVVM)"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State Management
  provider: ^6.1.2

  # Local Database (SQLite) - RUBRIK: CRUD SQLite
  sqflite: ^2.3.3+1
  path: ^1.9.0

  # Firebase - RUBRIK: Firebase Auth & Firestore
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4

  # Hardware Resources - RUBRIK: Hardware Resources
  image_picker: ^1.1.2
  location: ^7.0.0

  # Notifications - RUBRIK: Notifications
  awesome_notifications: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
