// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9JowuI-vUcmFknKDdCYV2FYsH-_KroOc',
    appId: '1:277898977053:web:7c5a7b9c78dfa1447dcbf4',
    messagingSenderId: '277898977053',
    projectId: 'testing-firebase-pbb',
    authDomain: 'testing-firebase-pbb.firebaseapp.com',
    storageBucket: 'testing-firebase-pbb.firebasestorage.app',
    measurementId: 'G-EVFCXFZ5DC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBReLPZOUjjgAGpGeMbFqEeth0hzeixrwk',
    appId: '1:277898977053:android:87f63828299b6c1f7dcbf4',
    messagingSenderId: '277898977053',
    projectId: 'testing-firebase-pbb',
    storageBucket: 'testing-firebase-pbb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBuIpF9T84m1-FS6KiTxPmF5KeUExjBCck',
    appId: '1:277898977053:ios:dabda7d8dcb7ab367dcbf4',
    messagingSenderId: '277898977053',
    projectId: 'testing-firebase-pbb',
    storageBucket: 'testing-firebase-pbb.firebasestorage.app',
    iosBundleId: 'com.example.pebebe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBuIpF9T84m1-FS6KiTxPmF5KeUExjBCck',
    appId: '1:277898977053:ios:dabda7d8dcb7ab367dcbf4',
    messagingSenderId: '277898977053',
    projectId: 'testing-firebase-pbb',
    storageBucket: 'testing-firebase-pbb.firebasestorage.app',
    iosBundleId: 'com.example.pebebe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9JowuI-vUcmFknKDdCYV2FYsH-_KroOc',
    appId: '1:277898977053:web:36adeabd3ded72747dcbf4',
    messagingSenderId: '277898977053',
    projectId: 'testing-firebase-pbb',
    authDomain: 'testing-firebase-pbb.firebaseapp.com',
    storageBucket: 'testing-firebase-pbb.firebasestorage.app',
    measurementId: 'G-30E0P1D69Y',
  );
}
